language: node_js
node_js:
- '12'
env:
  global:
  - DEPLOY_REPOSITORY="git@github.com:konnectors/opngo.git"
  - secure: j4+kIWMotlgL5w6R8smPCZ/mwt7fILsp682/wZIAiZHaUobj7Xz+gsdNN6FFf1A2LpCpastG5nsxg9qcGnnEWagnZSYh8R36Jrc4HZ+cBb8xDOUMKdNRRB/NC0rBdRyM/b25asC6mq/KPrGoHwGRWS/ssgsVOPRC3huS5IAsCMXxSw3w7moBYp4P9M9T4SuTjETO7yJHXx22PGpZSU8UEeKE3Ier0QBkB8upnI4RJe+OW/TEJ5kl6oBA+yGZpvsiRML2VBAzhCgdwP6KzXZkfJLEf43G/55/BP+fzDgLq9ZIPJeiL4yx2YUVz52YJuLQFtYVOq5pYM5cc+KsMFOMwfZ1FZezzclqkdGDYu2ExzYrIK0yetIgxttVshteF+UZtQzgVAcMjhvEnIulsgUI0uzLS72TcaHYl4ntLXgCXhZAxqwkoGKu6FfcCswZ9Qxp5rOuJek6Q6MqbU4Us9Vfo8qTOtSWyQCC2Gg1BUrfbUKKMN8yrlEHcAeErya20Hr8KWt6yCl5JyC4BicfHD3m6PyYrytXxGsREBu01Ed1mxUK+BBILFVByyOXjKwpl59fuiKtPiK1Ea5kc+nwxlqNHthjv2ZOcOBLb8i57T/YG2rtYCIZpaysPqZ5nMcPUiIJK4o8zuY7nF/Jd5I5FS/1YQ8d/+zLExYhlM1mDQRoOaA=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
- yarn run check
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_4a6a128cef3f_key -iv $encrypted_4a6a128cef3f_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
